public class Main {
    public static void main(String[] args) {
        System.out.println("задание №1");
        var dog = 8.0;
        System.out.println("начальное значение собаки " +dog);
        var cat = 3.6;
        System.out.println("начальное значение кошки " +cat);
        var paper = 763789;
        System.out.println("начальное значение бумаги " +paper);
        System.out.println("Задание №2");
        var dog1 = dog + 4;
        System.out.println("увеличили значение собаки " +dog1);
        var cat1 = cat +4;
        System.out.println("увеличили значение кошки " +cat1);
        var paper1 = paper +4;
        System.out.println("увеличили значение бумаги " +paper1);
        System.out.println("задание №3");
        var dog2 = dog1 - 3.5;
        System.out.println("уменьшили значение собаки " +dog2);
        var cat2 = cat1 -1.6;
        System.out.println("Уменьшили значение кошки " +cat2);
        var paper2 = paper1 - 7639;
        System.out.println("уменьшили значение бумаги " +paper2);
        System.out.println("Задание №4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("Задание №5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        System.out.println("Задание №6");
        var x = 78.2;
        System.out.println("вес первого боксёра " +x+ " кг");
        var y = 82.7;
        System.out.println("вес второго боксёра " +y+ " кг");
        var b = x + y;
        System.out.println("общий вес боксёров " +b+ " кг");
        var c = y - x;
        System.out.println("разница в вессе боксеров " +c+ " кг");
        System.out.println("Задание №7");
        var p = y % x;
        System.out.println("остаток от деления между двумя весами боксеров " +p);
        System.out.println("задание №8");
        var r = 640;
        var g = 8;
        var h = r / g;
        System.out.println("Всего работников в компании " +h+ " человек!");
        var j = h + 94;
        var q = r / j;
        System.out.println("Если в компании работает " +j+ " человек то всего " +q+ " часа работы может быть поделено между сотрудниками.");
    }
}